config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  match '/auth/user/callback', :to => 'sessions#create', :via => [:get, :post]
  get '/logout' => 'sessions#destroy', :as => :logout
  get 'auth/failure' => 'sessions#failure'

  resources :magazines do
    resources :articles
  end  

  resources :comments do
    member do
      post :child_comment
    end
  end    

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :magazine
  has_many :comments, :as => :commentable

  acts_as_commentable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
	has_many :articles
end

app/models/user.rb
class User < OmniAuth::Identity::Models::ActiveRecord
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_email!(session[:email]) if session[:email]
  rescue
    @current_user = nil
  end

  def authenticate
    if current_user.blank?
      redirect_to root_path, :flash => {:error => "Not Authorized"}
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def show
		@article = Article.where(id: params[:id]).first
	end	
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		article = Article.where(id: params[:article_id]).first
		comment = Comment.build_from( article, current_user.id, params[:comment])
		comment.save
		redirect_to magazine_article_path(magazine_id: article.magazine_id, id: article.id), flash: {notice: "Comment successfully posted..."}
	end	

	def child_comment
		comment = Comment.where(id: params[:id]).first
		article = comment.commentable
		child_comment = Comment.build_from( article, current_user.id, params[:comment])
		child_comment.save
		child_comment.move_to_child_of(comment)
		redirect_to magazine_article_path(magazine_id: article.magazine_id, id: article.id), flash: {notice: "Comment successfully posted..."}
	end	

	def destroy
		comment = Comment.where(id: params[:id]).first
		article = comment.commentable
		comment.destroy
		redirect_to magazine_article_path(magazine_id: article.magazine_id, id: article.id), flash: {notice: "Comment successfully deleted..."}
	end	
	
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController

	def index
		@magazines = Magazine.includes( articles: [:comments]).all
	end	

	def show
		@magazine = Magazine.where(id: params[:id]).first
	end	
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	skip_before_action :authenticate

	def new
	end	

	def create
		auth_hash = request.env['omniauth.auth']
		session[:email] = auth_hash['info']['email']
		if session[:email].present?
			redirect_to magazines_path, :flash => {:success => "Successfully Signed In.."}
		else
			redirect_to root_path, :flash => {:error => params[:message]}
		end	
	end	

	def failure
	    redirect_to request.referer, :flash => {:error => params[:message]}
  	end

	def destroy
	    session[:email] = nil
	    redirect_to root_path, :flash => {:success => 'User successfully logged out.'}
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def bootstrap_class_for flash_type
	    case flash_type
	      when :success
	        "alert-success"
	      when :error
	        "alert-danger"
	      when :alert
	        "alert-block"
	      when :notice
	        "alert-success"
	      else
	        flash_type.to_s
	    end
	end
end

app/views/articles/_child_comments.html.slim
-if comment.children.present?
	-comment.children.each do |c|
		.media
		    .media-left
		      img.media-object alt="64x64" data-holder-rendered="true" data-src="holder.js/64x64" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==" style=("width: 64px; height: 64px;") /
		    .media-body
		      h5#nested-media-heading.media-heading
		        = c.user.name
		        small
		        	| &nbsp; Posted on #{c.created_at}
		        a.anchorjs-link href="#nested-media-heading" 
		          span.anchorjs-icon
		      p = c.body
		      small 
		    	=link_to "#collapseComment#{c.id}", "data-toggle"=>"collapse", "data-parent"=>"#accordion", "aria-expanded"=>"true", "aria-controls"=>"collapseOne" do
		    		|Comments (#{c.children.count})
		    	-if ((c.user_id == current_user.id) && c.children.blank?)
			    	|&nbsp;|&nbsp;
			    	= link_to "Delete", c, data: {:confirm => 'Are you sure?'}, :method => :delete
		      div(id="collapseComment#{c.id}" class="panel-collapse collapse")
			    p
			    = render partial: 'child_comments', locals: {comment: c}
		hr      

= form_tag child_comment_comment_path(id: comment.id), method: :post do
	= text_area_tag :comment, nil, placeholder: "Comment...", class: "form-control", required: true
	br
	= submit_tag :submit, class: "btn btn-primary pull-right"
	p

app/views/articles/show.html.slim
.container
	h1 = @article.title
	p
		| Written By: 
		= @article.author
		span.pull-right
			= link_to 'Back', magazine_path(@article.magazine_id)
			| &nbsp;|&nbsp;
			= link_to 'Logout', logout_path
	hr
	= @article.body
	hr
	b Comments (#{@article.comment_threads.count})
	p
	br

	ul.media-list#accordion
		-@article.root_comments.order("created_at DESC").each do |comment|
			li.media
				.media-left
		        	img.media-object alt="64x64" data-holder-rendered="true" data-src="holder.js/64x64" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==" style=("width: 64px; height: 64px;") /
				.media-body
					h5#media-heading.media-heading
				        = comment.user.name
				        small
				        	| &nbsp; Posted on #{comment.created_at}
				        a.anchorjs-link href="#media-heading" 
				          span.anchorjs-icon
				    p = comment.body
				    small 
				    	=link_to "#collapseComment#{comment.id}", "data-toggle"=>"collapse", "data-parent"=>"#accordion", "aria-expanded"=>"true", "aria-controls"=>"collapseOne" do
				    		|Comments (#{comment.children.count})
				    	-if ((comment.user_id == current_user.id) && comment.children.blank?)
					    	|&nbsp;|&nbsp;
					    	= link_to "Delete", comment, data: {:confirm => 'Are you sure?'}, :method => :delete	
				    div(id="collapseComment#{comment.id}" class="panel-collapse collapse")
					    p
					    = render partial: 'child_comments', locals: {comment: comment}
			hr	    

	= form_tag comments_path(article_id: @article.id) do
		= text_area_tag :comment, nil, placeholder: "Comment...", class: "form-control", required: true
		br
		= submit_tag :submit, class: "btn btn-primary pull-right"

app/views/layouts/application.html.slim
doctype html
html
	head
    	title Magazine
    	= stylesheet_link_tag    'application', media: 'all'
    	= javascript_include_tag 'application'
    	= csrf_meta_tags 
  	body
  		= render 'shared/flash'
  		= yield 

app/views/magazines/index.html.slim
.container
	h1 Magazines
	span.pull-right
		= link_to 'Logout', logout_path
	hr
	-@magazines.in_groups_of(4,false).each do |magazines|
		.row
			-magazines.each do |magazine|
				.col-sm-3.col-xs-6
					.panel.panel-primary.text-center
						.panel-body
							h4 = link_to magazine.name, magazine_path(magazine)
							p = magazine.published_by
						.panel-footer
							.row
								.col-sm-6
									|#{magazine.articles.count} Articles
								.col-sm-6
									|#{magazine.articles.map(&:comments).count} Comments

app/views/magazines/show.html.slim
.container
	h1 = @magazine.name
	p
		| Published By: 
		= @magazine.published_by
		span.pull-right
			= link_to 'Back', magazines_path
			| &nbsp;|&nbsp;
			= link_to 'Logout', logout_path
	hr
	-@magazine.articles.in_groups_of(4,false).each do |articles|
		.row
			-articles.each do |article|
				.col-sm-3.col-xs-6
					.panel.panel-primary.text-center
						.panel-body
							h4 = link_to article.title, magazine_article_path(magazine_id: @magazine.id, id: article.id)
							p = article.author
						.panel-footer
							.row
								.col-sm-6
									|#{article.comment_threads.count} Comments
								.col-sm-6
									

app/views/shared/_flash.html.slim
.container
	- flash.each do |type, message|
	  br
	  div(class="alert #{bootstrap_class_for(type.to_sym)} fade in")
	    button.close data-dismiss="alert"x
	    = message